
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xksggzqcgfiochciwhih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrc2dnenFjZ2Zpb2NoY2l3aGloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Mjg2MDQsImV4cCI6MjA2NjQwNDYwNH0.T2bxgGBHXBfzHJ4L9-AkHl8n9R3aF9AkOZz9qHXlmNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
