
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfcanknjipqulsbgjmmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmY2Fua25qaXBxdWxzYmdqbW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTM0NTYsImV4cCI6MjA2NTM2OTQ1Nn0.GiDtHGX8mdQhq8EQztrpvCwKeW6AoEOJl7mt9E_8SoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
